refactor

diff --git a/limakube b/limakube
--- a/limakube
+++ b/limakube
@@ -7,6 +7,7 @@ export LIMA_HOME_DIR=/home/${USER}.linux # avoid using LIMA_HOME to not override
 export LAUNCHD_NAME=com.abiosoft.limakube.plist
 export LAUNCHD_FILE="$HOME/Library/LaunchAgents/$LAUNCHD_NAME"
 export SSH_PORT=68822
+export ENABLE_KUBERNETES=""
 
 # init
 mkdir -p "$CONF_DIR"
@@ -17,28 +18,33 @@ export ARCH=amd64
 
 print_usage() (
     cat <<EOF
-usage: lima <command>
+usage: limakube <command>
 
 commands:
-  start [ --kubernetes ]
-    Start (and/or provision) limakube vm with docker.
-    To provision with kubernetes, specify --kubernetes.
+  start [--kubernetes]
+    Start (and/or provision) limakube VM with docker (and kubernetes
+    if --kubernetes is passed).
 
   stop
-    Stop the limakube vm.
+    Stop the limakube VM.
 
   delete
-    Delete and teardown limakube vm and settings.
+    Delete and teardown the limakube VM and settings.
+
+  ssh
+    SSH into the limakube VM.
+
+  reset
+    Reset the kubernetes cluster.
 
   -h, --help
-  show this help
-
+    Show this help
 EOF
     if [ -z "$1" ]; then exit 0; else exit 1; fi
 )
 
 log() (
-    echo >&2 $@
+    echo >&2 "$@"
 )
 
 config_file() (
@@ -68,7 +74,10 @@ containerd:
 firmware:
   legacyBIOS: false
 EOF
+)
 
+assert_vm_running() (
+    lima uname &>/dev/null || (echo $LIMA_INSTANCE VM is not running. Run \'$LIMA_INSTANCE start\' to start limakube && exit 1)
 )
 
 launchd_file() (
@@ -108,6 +117,7 @@ EOF
 )
 
 check_deps() (
+    set -eu
     command -v lima || (echo lima not found. Run 'brew install lima' to install. && exit 1)
     command -v docker || (echo docker not found. Run 'brew install docker' to install. && exit 1)
 )
@@ -116,23 +126,14 @@ check_deps_k8s() (
     command -v kubectl || (echo kubectl not found. Run 'brew install kubectl' to install. && exit 1)
 )
 
-start_vm() (
-    set -eux
-    if [ -f "$LIMA_DIR" ]; then
-        limactl start $LIMA_INSTANCE
-    else
-        config_file
-        limactl start limakube.yaml
-        rm limakube.yaml
-    fi
-)
-
-stop_vm() (
-    [ -d "$HOME/.lima/$LIMA_INSTANCE" ] && limactl stop $LIMA_INSTANCE
+kube() (
+    lima minikube --profile limakube "$@"
 )
 
 provision_docker() (
-    set -eux
+    lima command -v docker && exit 0
+    set -eu
+
     # docker
     lima sudo apt -y install docker.io
     lima sudo usermod -aG docker $USER
@@ -143,27 +144,28 @@ provision_docker() (
     limactl stop
     limactl start
     launchctl load "$LAUNCHD_FILE"
+)
+
+teardown_docker() (
+    # remove socket service
+    launchctl unload $LAUNCHD_FILE
+)
+
+start_docker() (
+    set -eu
+    lima sudo service docker start
     launchctl start "$LAUNCHD_NAME"
 )
 
-kube() (
-    lima minikube --profile limakube "$@"
-)
-
-provision_minikube() (
-    set -eux
-    # minikube
-    lima curl -L -o /tmp/minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-${ARCH}
-    lima sudo install /tmp/minikube /usr/local/bin/minikube
-    kube start --driver=none
-
-    # kubectl
-    lima curl -L -o /tmp/kubectl https://dl.k8s.io/release/v1.22.0/bin/linux/${ARCH}/kubectl
-    lima sudo install /tmp/kubectl /usr/local/bin/kubectl
+stop_docker() (
+    set -eu
+    lima sudo service docker stop
+    launchctl stop $LAUNCHD_NAME
 )
 
 provision_kubeconfig() (
-    set -eux
+    [ -f "$HOME/.kube/.limakube" ] && exit 0
+    set -eu
 
     # ascertain deps for kubernetes
     check_deps_k8s
@@ -191,50 +193,136 @@ provision_kubeconfig() (
     # set combined config as new config
     cp "$HOST_DIR/lima-config" "$HOST_DIR/config"
 
-    # hack to indicate provision has been done
-    touch "$HOME/.kube/.limakube"
+    # provision flag to indicate provision has been done
+    touch "$HOST_DIR/.limakube"
 
     # clean up dirt
     rm "$HOST_DIR/lima-config"
 )
 
-provision_vm() (
-    set -eux
-    lima command -v docker || provision_docker
-    lima command -v minikube || provision_minikube
+teardown_kubeconfig() (
+    # reset provision flag
+    rm -rf "$HOME/.kube/.limakube"
+    # unset kube config
+    kubectl config unset users.limakube
+    kubectl config unset contexts.limakube
+    kubectl config unset clusters.limakube
+)
+
+provision_minikube() (
+    lima command -v minikube && exit 0
+    set -eu
+
+    # minikube
+    lima curl -L -o /tmp/minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-${ARCH}
+    lima sudo install /tmp/minikube /usr/local/bin/minikube
+    kube start --driver=none
+
+    # kubectl
+    lima curl -L -o /tmp/kubectl https://dl.k8s.io/release/v1.22.0/bin/linux/${ARCH}/kubectl
+    lima sudo install /tmp/kubectl /usr/local/bin/kubectl
+)
+
+teardown_minikube() (
+    kube delete
+    teardown_kubeconfig
 )
 
 start_minikube() (
-    set -eux
+    set -eu
     kube status || exit 0
     kube start --driver=none
-    [ -f "$HOME/.kube/.limakube" ] || provision_kubeconfig
+    provision_kubeconfig
 )
 
 stop_minikube() (
     kube status && kube stop
 )
 
-reset_minikube() (
-    set -eux
-    kube status || exit 0
-    kube delete
-    kube start --driver=none
+provision_vm() (
+    set -eu
+    provision_docker
+    [ -n "$ENABLE_KUBERNETES" ] && provision_minikube
 )
 
-teardown() (
-    set -eux
+stop_vm() (
+    set -eu
+    assert_vm_running
+    stop_minikube
+    stop_docker
+    limactl stop $LIMA_INSTANCE
+)
+
+teardown_vm() (
+    set -eu
+    assert_vm_running
+
+    teardown_minikube
+    teardown_docker
 
     # delete vm
     stop_vm
     limactl delete $LIMA_INSTANCE
-    rm -rf $HOME/.kube/.limakube
-
-    # unset kube config
-    kubectl config unset users.limakube
-    kubectl config unset contexts.limakube
-    kubectl config unset clusters.limakube
-
-    # remove socket service
-    launchctl unload $LAUNCHD_FILE
 )
+
+start_vm() (
+    set -eu
+
+    [ "$1" = "--kubernetes" ] && export ENABLE_KUBERNETES=1
+
+    if [ -f "$LIMA_DIR" ]; then
+        limactl start $LIMA_INSTANCE
+    else
+        config_file
+        limactl start limakube.yaml
+        rm limakube.yaml
+    fi
+
+    provision_vm
+    start_docker
+    start_minikube
+)
+
+lima_ssh() (
+    set -eu
+    assert_vm_running
+    lima
+)
+
+reset_minikube() (
+    set -eu
+    assert_vm_running
+    kube status || (echo Kubernetes is not enabled. && exit 0)
+    kube delete
+    teardown_minikube
+    kube start --driver=none
+)
+
+case "$1" in
+start)
+    shift
+    start_vm "$@"
+    ;;
+stop)
+    stop_vm
+    ;;
+delete)
+    teardown_vm
+    ;;
+ssh)
+    lima_ssh
+    ;;
+reset)
+    reset_minikube
+    ;;
+-h | --help)
+    print_usage
+    ;;
+"")
+    print_usage 1
+    ;;
+*)
+    log "invalid arg '$1'. view help with 'limakube --help'."
+    exit 1
+    ;;
+esac
